import { SCENE_LOCATION_TYPES, SCENE_OBJECT_TYPES, SCENE_ENTITY_ROLES } from "@/engine";
/** Same fact contract in the wire schema and the system prompt. */
export const SCENE_FACTS_PROMPT = `On start_encounter, include optional "scene" to translate the PUBLIC adventure context into structured facts:
{"locationType":"office","label":"Kiro's office","crowd":"none","entities":[{"id":"kiro","name":"Kiro","role":"worker"}],"objects":[{"id":"desk","label":"Kiro's desk","kind":"workstation"}],"entrances":[{"id":"entry","label":"Reception entrance","kind":"public"}],"relationships":[{"entity":"kiro","relation":"works_at","target":"desk"}]}.
Location types: ${SCENE_LOCATION_TYPES.join(", ")}. Object kinds: ${SCENE_OBJECT_TYPES.join(", ")}. Person roles: ${SCENE_ENTITY_ROLES.join(", ")}.
Preserve established names and stable IDs; an enemy mentioned in scene.entities MUST use its enemies key/name. Additional people are neutral, unarmed bystanders, never extra hostiles or allies. Include only people actually present, known objects/entrances, and public relationships from the current adventure. Never reveal hidden beat truths. Do not invent requirements just to fill arrays. Missing lists are empty and missing crowd is none. Crowd none/sparse/busy adds 0/2/5 generic tactical bystanders; it is a bounded representation, not a literal census.
Use near, guards or works_at for a person's placement relationship to one named object, entrance or person. One relationship per person; no cycles. These express proximity, not new combat abilities. Never send coordinates, distances, collision rectangles, rotations, HP or statistics.
Supported ingredients: intersection: vehicle/vendor/freight/utilities; alley: freight/utilities; residential: vehicle/garden; office: workstation/reception/meeting/seating/server; nightclub: bar/seating/performance; warehouse: racking/freight/reception/workbench; garage: vehicle/reception/workbench. Request at most one of each important ingredient unless the fiction requires more. Do not turn an unsupported object into a different one.
Interior entrances are public/service; warehouse and garage also support loading. Exterior recipes support front entrances to CLOSED facades. Interior openings are always OPEN. Locked doors, upper-floor access and other unsupported geometry cannot be promised. Rooftops and other unsupported locations retain the authored arena: omit scene rather than mislabel the location.
The engine selects a coherent variation when details are missing, fits and validates ingredients, and saves it before initiative. It may reject facts that cannot fit. Never invent placements in narration. ESTABLISHED SCENE FACTS override your suggestions; SAVED SCENE is immutable. Never respawn a resolved scene.`;
