/**
 * The structured contract the LIFE model must return, plus a tolerant
 * normalizer — the same pattern as gmResponse.ts, but with a vocabulary that
 * makes job behaviour unexpressible: there is no start_encounter, no attack,
 * no advance_beat, and no way to accept a job.
 */
import { z } from "zod";
import { isAnswerableQuestion } from "@/engine";

export const LIFE_ACTION_KINDS = [
  "skill_check",
  "opposed_check",
  "spend",
  "use_item",
  "travel",
  "rest",
  "pay_bills",
  "repair_armor",
  "hook_offer",
  "none",
] as const;

/** What the engine should resolve out of the player's stated intent. */
export const LifeProposedActionSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("skill_check"),
    skillId: z.string(),
    dv: z.number().int(),
    intent: z.string(),
  }),
  z.object({
    kind: z.literal("opposed_check"),
    skillId: z.string(),
    npcKey: z.string(),
    npcName: z.string(),
    opposingSkillId: z.string(),
    opposingSkillLevel: z.number().int(),
    opposingStatValue: z.number().int(),
    intent: z.string(),
  }),
  z.object({ kind: z.literal("spend"), amount: z.number().int(), reason: z.string() }),
  z.object({ kind: z.literal("use_item"), item: z.string(), quantity: z.number().int() }),
  z.object({ kind: z.literal("pay_bills") }),
  z.object({ kind: z.literal("repair_armor") }),
  z.object({
    kind: z.literal("travel"),
    destination: z.string().optional(),
    /** A compass heading the player asked for; the engine picks the district. */
    direction: z.string().optional(),
    extent: z.enum(["near", "far"]).optional(),
    /** How they said they were getting there: "foot" or "cab". */
    mode: z.string().optional(),
    /** How far they said to go, in city blocks, when they put a distance on it. */
    blocks: z.number().optional(),
    minutes: z.number().int(),
  }),
  z.object({ kind: z.literal("rest"), hours: z.number().int() }),
  // A hook offer carries NOTHING. The job on the wire was generated by the
  // engine before this turn ran and the model was shown it; letting the model
  // restate the title, the patron or the fee is exactly how the offer and the
  // job it starts drift apart.
  z.object({ kind: z.literal("hook_offer") }),
  z.object({ kind: z.literal("none") }),
]);
export type LifeProposedAction = z.infer<typeof LifeProposedActionSchema>;

/**
 * World changes the model may record. There is deliberately NO clock here any
 * more: a dial the model can name, size and move is not a clock. Pressure is
 * reported as observations (see below) and priced by the engine.
 */
export const LifeDeltaSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("set_flag"), flag: z.string() }),
  z.object({ kind: z.literal("npc_disposition"), npcKey: z.string(), delta: z.number().int() }),
  z.object({ kind: z.literal("note"), text: z.string() }),
]);
export type LifeDelta = z.infer<typeof LifeDeltaSchema>;

/** One of the three offered actions, as the player sees it on a card. */
export type LifeActionCard = {
  label: string;
  description: string;
  timeMinutes: number;
  knownCost: number | null;
  skillId: string | null;
};

export type LifeSituationCard = { title: string; description: string };

export type LifeNewSituation = {
  key: string;
  category: "need" | "people" | "opportunity" | "pressure";
  title: string;
  summary: string;
  npcKey: string | null;
  severity: number;
  dueDay: number | null;
};

/** One thing the fiction noticed, for the engine to price. */
export type LifeObservation = { observation: string; factionId: string | null };

export type LifeResponse = {
  situation: LifeSituationCard;
  /**
   * Offered actions. Empty on an ordinary turn: the player types what they do.
   * Populated only when the turn was an explicit request for options.
   */
  actions: LifeActionCard[];
  /**
   * How long what the player just did took them, in minutes. Advisory: the
   * engine clamps it (see clampActionMinutes) and owns the clock, and ignores it
   * entirely on a turn whose actions carry their own duration.
   */
  timeSpent: number;
  resolution: string | null;
  proposedActions: LifeProposedAction[];
  deltas: LifeDelta[];
  /**
   * What the turn noticed, from the engine's closed vocabulary. The model
   * reports; engine/clocks.ts decides what each one costs.
   */
  observations: LifeObservation[];
  newSituation: LifeNewSituation | null;
  /**
   * One thing the turn needed to know and could not: "Is the ripperdoc still
   * open at this hour?" The engine rolls for it and hands the answer back on the
   * NEXT turn, so the model writes this one without knowing. Null when the turn
   * did not need to ask, which is most of them.
   */
  question: string | null;
};

/**
 * The wire schema is deliberately loose. Models drift on field names and
 * nesting; rejecting the whole turn over a renamed key would cost the player a
 * turn, so everything is narrowed in normalizeLifeResponse instead.
 */
export const LifeWireResponseSchema = z.object({
  situation: z.object({ title: z.string().nullish(), description: z.string().nullish() }).nullish(),
  actions: z.array(z.unknown()).nullish(),
  timeSpent: z.number().nullish(),
  resolution: z.string().nullish(),
  proposedActions: z.array(z.unknown()).nullish(),
  deltas: z.array(z.unknown()).nullish(),
  observations: z.array(z.unknown()).nullish(),
  newSituation: z.unknown().nullish(),
  question: z.unknown().nullish(),
});
export type LifeWireResponse = z.infer<typeof LifeWireResponseSchema>;

type Loose = Record<string, unknown>;

function str(value: unknown): string | undefined {
  if (typeof value === "string" && value.trim()) return value.trim();
  return undefined;
}

function num(value: unknown): number | undefined {
  if (typeof value === "number" && Number.isFinite(value)) return Math.round(value);
  if (typeof value === "string") {
    const parsed = Number(value.replace(/[^0-9.-]/g, ""));
    if (Number.isFinite(parsed)) return Math.round(parsed);
  }
  return undefined;
}

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}

/** Printed DV ladder; anything else is snapped to the nearest printed value. */
const DV_LADDER = [9, 13, 15, 17, 21, 24, 29];

function snapDv(value: number | undefined): number {
  if (value === undefined) return 13;
  let best = DV_LADDER[0] as number;
  for (const dv of DV_LADDER) {
    if (Math.abs(dv - value) < Math.abs(best - value)) best = dv;
  }
  return best;
}

/** Longest single Life action, mirroring the engine's clamp. */
const MAX_MINUTES = 12 * 60;

function normalizeActions(raw: unknown): LifeActionCard[] {
  if (!Array.isArray(raw)) return [];
  const out: LifeActionCard[] = [];
  for (const item of raw) {
    if (!item || typeof item !== "object") continue;
    const a = item as Loose;
    const label = str(a["label"]) ?? str(a["title"]) ?? str(a["text"]);
    if (!label) continue;
    const cost = num(a["knownCost"] ?? a["known_cost"] ?? a["cost"]);
    out.push({
      label,
      description: str(a["description"]) ?? str(a["detail"]) ?? "",
      timeMinutes: clamp(
        num(a["timeMinutes"] ?? a["time_minutes"] ?? a["minutes"]) ?? 15,
        0,
        MAX_MINUTES,
      ),
      knownCost: cost !== undefined && cost > 0 ? cost : null,
      skillId: str(a["skillId"]) ?? str(a["skill_id"]) ?? str(a["skill"]) ?? null,
    });
    if (out.length === 4) break;
  }
  return out;
}

function normalizeProposed(raw: unknown, warn: (m: string) => void): LifeProposedAction[] {
  if (!Array.isArray(raw)) return [];
  const out: LifeProposedAction[] = [];
  for (const item of raw) {
    if (!item || typeof item !== "object") continue;
    const a = item as Loose;
    const kindRaw = (str(a["kind"]) ?? str(a["type"]) ?? "").toLowerCase().replace(/[\s-]+/g, "_");
    const skillId = str(a["skillId"]) ?? str(a["skill_id"]) ?? str(a["skill"]);
    const opposingSkillId = str(a["opposingSkillId"]) ?? str(a["opposing_skill_id"]);
    const intent = str(a["intent"]) ?? str(a["description"]) ?? "";

    if (kindRaw === "hook_offer" || kindRaw === "job_offer" || kindRaw === "hook") {
      // Any title, patron or fee the model attached is discarded rather than
      // merged: the offer is read off the mission the engine already generated.
      out.push({ kind: "hook_offer" });
      continue;
    }
    // Bills and repairs are named jobs the engine prices itself, so they are
    // matched BEFORE the generic spend branch — a model that helpfully attaches
    // its own guess at the rent must not turn into an arbitrary withdrawal.
    if (kindRaw === "pay_bills" || kindRaw === "bills" || kindRaw === "pay_rent") {
      out.push({ kind: "pay_bills" });
      continue;
    }
    if (kindRaw === "spend" || (num(a["amount"]) !== undefined && !skillId)) {
      const amount = num(a["amount"]) ?? num(a["cost"]);
      if (amount === undefined || amount <= 0) continue;
      out.push({ kind: "spend", amount, reason: str(a["reason"]) ?? intent });
      continue;
    }
    if (kindRaw === "repair_armor" || kindRaw === "repair") {
      out.push({ kind: "repair_armor" });
      continue;
    }
    if (kindRaw === "use_item" || kindRaw === "use") {
      const item = str(a["item"]) ?? str(a["itemId"]) ?? str(a["item_id"]) ?? str(a["name"]);
      if (!item) {
        warn("Life model used an item it did not name, dropped.");
        continue;
      }
      out.push({ kind: "use_item", item, quantity: clamp(num(a["quantity"]) ?? 1, 1, 99) });
      continue;
    }
    if (kindRaw === "travel") {
      const destination = str(a["destination"]) ?? str(a["to"]);
      const direction = str(a["direction"]) ?? str(a["heading"]) ?? str(a["bearing"]);
      const extentRaw = (str(a["extent"]) ?? "").toLowerCase();
      const mode = str(a["mode"]) ?? str(a["by"]) ?? str(a["transport"]);
      const blocks = num(a["blocks"]) ?? num(a["distanceBlocks"]);
      out.push({
        kind: "travel",
        ...(destination ? { destination } : {}),
        ...(direction ? { direction } : {}),
        ...(mode ? { mode } : {}),
        ...(blocks && blocks > 0 ? { blocks: clamp(blocks, 1, 200) } : {}),
        ...(extentRaw === "far" || extentRaw === "near"
          ? { extent: extentRaw as "near" | "far" }
          : {}),
        minutes: clamp(num(a["minutes"]) ?? 40, 0, MAX_MINUTES),
      });
      continue;
    }
    if (kindRaw === "rest" || kindRaw === "sleep") {
      out.push({ kind: "rest", hours: clamp(num(a["hours"]) ?? 8, 1, 24) });
      continue;
    }
    if (kindRaw === "opposed_check" || (skillId && opposingSkillId)) {
      const npcName = str(a["npcName"]) ?? str(a["npc_name"]) ?? str(a["opponent"]);
      const npcKey = str(a["npcKey"]) ?? str(a["npc_key"]) ?? npcName;
      if (!skillId || !opposingSkillId || !npcKey || !npcName) {
        warn("Life model proposed an opposed check missing a side, dropped.");
        continue;
      }
      out.push({
        kind: "opposed_check",
        skillId,
        npcKey,
        npcName,
        opposingSkillId,
        opposingSkillLevel: clamp(
          num(a["opposingSkillLevel"] ?? a["opposing_skill_level"]) ?? 3,
          0,
          10,
        ),
        opposingStatValue: clamp(
          num(a["opposingStatValue"] ?? a["opposing_stat_value"]) ?? 5,
          1,
          10,
        ),
        intent,
      });
      continue;
    }
    if (kindRaw === "skill_check" || skillId) {
      if (!skillId) continue;
      out.push({ kind: "skill_check", skillId, dv: snapDv(num(a["dv"])), intent });
      continue;
    }
    if (kindRaw === "none") continue;
    // Anything job-shaped (an encounter, an attack, a beat advance) has no
    // vocabulary in Life and is dropped rather than half-understood.
    if (kindRaw) warn(`Life model proposed "${kindRaw}", which Life cannot resolve. Dropped.`);
  }
  return out;
}

function normalizeDeltas(raw: unknown): LifeDelta[] {
  if (!Array.isArray(raw)) return [];
  const out: LifeDelta[] = [];
  for (const item of raw) {
    if (typeof item === "string") {
      const text = str(item);
      if (text) out.push({ kind: "note", text });
      continue;
    }
    if (!item || typeof item !== "object") continue;
    const d = item as Loose;
    const kind = (str(d["kind"]) ?? str(d["type"]) ?? "").toLowerCase();
    const flag = str(d["flag"]);
    const npcKey = str(d["npcKey"]) ?? str(d["npc_key"]) ?? str(d["npc"]);
    // A model reaching for a clock is reaching for authority it does not have.
    // Dropped rather than approximated: what it noticed belongs in observations.
    const clockKey = str(d["clockKey"]) ?? str(d["clock_key"]) ?? str(d["clock"]);
    if (kind === "clock" || clockKey) continue;
    if (kind === "npc_disposition" || (npcKey && num(d["delta"]) !== undefined)) {
      if (!npcKey) continue;
      out.push({ kind: "npc_disposition", npcKey, delta: clamp(num(d["delta"]) ?? 0, -3, 3) });
      continue;
    }
    if (kind === "set_flag" || flag) {
      if (!flag) continue;
      out.push({ kind: "set_flag", flag });
      continue;
    }
    const text = str(d["text"]) ?? str(d["note"]) ?? str(d["summary"]);
    if (text) out.push({ kind: "note", text });
  }
  return out;
}

/** Shape-check only. Whether these name real observations is the engine's call. */
function normalizeObservations(raw: unknown): LifeObservation[] {
  if (!Array.isArray(raw)) return [];
  const out: LifeObservation[] = [];
  for (const item of raw) {
    if (typeof item === "string") {
      out.push({ observation: item, factionId: null });
      continue;
    }
    if (!item || typeof item !== "object") continue;
    const o = item as Loose;
    const observation = str(o["observation"]) ?? str(o["kind"]) ?? str(o["what"]);
    if (!observation) continue;
    out.push({
      observation,
      factionId: str(o["factionId"]) ?? str(o["faction_id"]) ?? str(o["faction"]) ?? null,
    });
    if (out.length === 6) break;
  }
  return out;
}

/** A question survives only if a yes/no table could answer it. */
function normalizeQuestion(raw: unknown): string | null {
  const text = typeof raw === "string" ? raw : str((raw as Loose | null)?.["question"]);
  if (!text) return null;
  return isAnswerableQuestion(text.trim()) ? text.trim() : null;
}

function normalizeNewSituation(raw: unknown): LifeNewSituation | null {
  if (!raw || typeof raw !== "object") return null;
  const s = raw as Loose;
  const title = str(s["title"]);
  if (!title) return null;
  const categoryRaw = (str(s["category"]) ?? "opportunity").toLowerCase();
  const category = (["need", "people", "opportunity", "pressure"] as const).includes(
    categoryRaw as "need",
  )
    ? (categoryRaw as LifeNewSituation["category"])
    : "opportunity";
  const key =
    str(s["key"]) ??
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "");
  return {
    key,
    category,
    title,
    summary: str(s["summary"]) ?? str(s["description"]) ?? "",
    npcKey: str(s["npcKey"]) ?? str(s["npc_key"]) ?? null,
    severity: clamp(num(s["severity"]) ?? 2, 1, 5),
    dueDay: num(s["dueDay"] ?? s["due_day"]) ?? null,
  };
}

export type NormalizeLifeOptions = { onWarn?: (message: string) => void };

export function normalizeLifeResponse(
  wire: LifeWireResponse,
  options: NormalizeLifeOptions = {},
): LifeResponse {
  const warn = options.onWarn ?? ((m: string) => console.warn(m));
  return {
    situation: {
      title: str(wire.situation?.title) ?? "Night City, and you in it",
      description: str(wire.situation?.description) ?? "",
    },
    actions: normalizeActions(wire.actions),
    timeSpent: clamp(num(wire.timeSpent) ?? 0, 0, MAX_MINUTES),
    resolution: str(wire.resolution) ?? null,
    proposedActions: normalizeProposed(wire.proposedActions, warn),
    deltas: normalizeDeltas(wire.deltas),
    // Left raw on purpose: engine/clocks.ts owns the vocabulary, and
    // features/campaign/pressure.ts is the one place it is checked against.
    observations: normalizeObservations(wire.observations),
    newSituation: normalizeNewSituation(wire.newSituation),
    // Kept only if an oracle could actually answer it; the engine's own
    // predicate decides, so a model asking "what is in the crate?" is dropped
    // here rather than handed a yes/no that means nothing.
    question: normalizeQuestion(wire.question),
  };
}
