/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StyleRouteImport } from './routes/style'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as ApiGeneratePortraitRouteImport } from './routes/api/generate-portrait'
import { Route as AuthenticatedCharacterIdRouteImport } from './routes/_authenticated/character.$id'
import { Route as AuthenticatedPlayIdRouteImport } from './routes/_authenticated/play.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleRoute = StyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiGeneratePortraitRoute = ApiGeneratePortraitRouteImport.update({
  id: '/api/generate-portrait',
  path: '/api/generate-portrait',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCharacterIdRoute =
  AuthenticatedCharacterIdRouteImport.update({
    id: '/character/$id',
    path: '/character/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayIdRoute = AuthenticatedPlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/style': typeof StyleRoute
  '/create': typeof AuthenticatedCreateRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/character/$id': typeof AuthenticatedCharacterIdRoute
  '/play/$id': typeof AuthenticatedPlayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/style': typeof StyleRoute
  '/create': typeof AuthenticatedCreateRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/character/$id': typeof AuthenticatedCharacterIdRoute
  '/play/$id': typeof AuthenticatedPlayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/style': typeof StyleRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/_authenticated/character/$id': typeof AuthenticatedCharacterIdRoute
  '/_authenticated/play/$id': typeof AuthenticatedPlayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/style'
    | '/create'
    | '/roster'
    | '/api/generate-portrait'
    | '/character/$id'
    | '/play/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/style'
    | '/create'
    | '/roster'
    | '/api/generate-portrait'
    | '/character/$id'
    | '/play/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/style'
    | '/_authenticated/create'
    | '/_authenticated/roster'
    | '/api/generate-portrait'
    | '/_authenticated/character/$id'
    | '/_authenticated/play/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  StyleRoute: typeof StyleRoute
  ApiGeneratePortraitRoute: typeof ApiGeneratePortraitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style': {
      id: '/style'
      path: '/style'
      fullPath: '/style'
      preLoaderRoute: typeof StyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/generate-portrait': {
      id: '/api/generate-portrait'
      path: '/api/generate-portrait'
      fullPath: '/api/generate-portrait'
      preLoaderRoute: typeof ApiGeneratePortraitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/character/$id': {
      id: '/_authenticated/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof AuthenticatedCharacterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$id': {
      id: '/_authenticated/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof AuthenticatedPlayIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedCharacterIdRoute: typeof AuthenticatedCharacterIdRoute
  AuthenticatedPlayIdRoute: typeof AuthenticatedPlayIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedCharacterIdRoute: AuthenticatedCharacterIdRoute,
  AuthenticatedPlayIdRoute: AuthenticatedPlayIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  StyleRoute: StyleRoute,
  ApiGeneratePortraitRoute: ApiGeneratePortraitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
